### ISSUE TITLE
Wrong Problem also accepted

### ISSUE THREAD

**Issue by malavancs** [theSage21/openJudge#31] opened 2018-01-26 05:34 UTC
Even an invalid program also accepted.

**Comment by theSage21** [comment] 2018-01-26 05:49
Can you add an example test case?

**Comment by malavancs** [comment] 2018-01-26 08:08
[ContestData.zip](https://github.com/theSage21/openJudge/files/1667037/ContestData.zip)
![screen shot 2018-01-26 at 1 35 25 pm](https://user-images.githubusercontent.com/25359639/35430401-1299e76e-029e-11e8-93f5-3ce538ca28a1.png)
I have attached contest data and the result page screenshot

**Comment by theSage21** [comment] 2018-01-27 02:33
I understand the problem to be a Caesar box cipher. I've written the following program for it.

```python
import math

x = input()
x = x.replace(' ', '*')
box, row = [], []
square_side =math.ceil(len(x)**0.5)
for i in x:
    if len(row) >= square_side:
        box.append(row)
        row = []
    row.append(i)

if row:
    row += ['.'] * (square_side - len(row))
box.append(row)


message = ''
for i in range(square_side):
    for j in box:
        message += j[i]
print(message)
```

which produces the output of `Lohdsoe*ewhdtt*ioasoscpy**ah*.gtn*t.` against the expectation of `Lohdsoe*ewhdtt*ioasoscpy**ah*.gtn*t.` This program should be accepted but is rejected AFAIK.

Can @malavancs confirm? Corresponding contest JSON is [here](https://gist.github.com/theSage21/b34c87201873ee81f3fd3a81eace55fa)

**Comment by malavancs** [comment] 2018-01-27 14:34
The correct  java solution is here.


import java.util.Scanner; 

/** 
 * 
 * @author malavan 
 */ 
public class Solution { 

    /** 
     * @param args the command line arguments 
     */ 
     
     
     
    public static void main(String[] args) { 
         
         
       String input;      
       Scanner bucky = new Scanner(System.in); 
       input = bucky.nextLine(); 
        
       int size = input.length(); 
       int row; 
       if(size/6==0) 
       { 
           row = size/6; 
            
       } 
       else 
       { 
           row = size/6+1; 
       } 
        
       if(size/6 != 0) 
       { 
           for(int m=0;m              input =  input.concat("."); 
       } 

       String s = ""; 
        
       char[][] arr = new char[row][6]; 
        
        
       int k=0; 
       for(int i=0;i       { 
           for(int j=0;j<6;j++) 
           { 
               if(input.charAt(k)==' ') 
               arr[i][j] = '*'; 
               else 
               arr[i][j] = input.charAt(k); 
               k++; 
                
           } 
            
       } 
        
        
        
        
       System.out.println(); 
       for(int i=0;i<6;i++) 
       { 
           for(int j=0;j           { 
                
               System.out.print(arr[j][i]); 
           } 
           //System.out.println(); 
       } 
       bucky.next(); 
        
    } 
     
} 

But the wrong solution also accepted with .85 points

**Comment by malavancs** [comment] 2018-01-27 14:41
The json file looks same. 

```java
import java.util.Scanner;

/**
 *
 * @author malavan
 */
public class Solution {

    /**
     * @param args the command line arguments
     */
    
    
    
    public static void main(String[] args) {
        
        
       String input;     
       Scanner bucky = new Scanner(System.in);
       input = bucky.nextLine();
       
       int size = input.length();
       int row;
       if(size/6==0)
       {
           row = size/6;
           
       }
       else
       {
           row = size/6+1;
       }
       
       if(size/6 != 0)
       {
           for(int m=0;m<size/6;m++)
              input =  input.concat(".");
       }

       String s = "";
       
       char[][] arr = new char[row][6];
       
       
       int k=0;
       for(int i=0;i<row;i++)
       {
           for(int j=0;j<6;j++)
           {
               if(input.charAt(k)==' ')
               arr[i][j] = '*';
               else
               arr[i][j] = input.charAt(k);
               k++;
               
           }
           
       }
       
       
       
       

       for(int i=0;i<6;i++)
       {
           for(int j=0;j<row;j++)
           {
               
               System.out.print(arr[j][i]);
           }
           //System.out.println();
       }
       
       
    }
    
}
```


Above code is the correct code accepted with 1.0;
But the wrong code also accepted with 0.85.

**Comment by theSage21** [comment] 2018-01-28 04:15
Can you paste outputs of the correct and wrong code? That should let us compare if the problem is in OpenJudge or the user submitted code.

**Comment by malavancs** [comment] 2018-01-28 07:24
The program print only 
System.out.println("");
I tried the following code
`Print ("Hello world")`
Even it also accepted

**Comment by theSage21** [comment] 2018-01-28 07:57
Since this behavior is not seen in other languages (I tested with Python2/3, G++, GCC, lua) we can assume that there's something wrong with the JAVA wrapper. On investigation we discover that even by submitting invalid Java, for example the program being `asdfasdf` the code is still accepted as correct.

This behavior is stopped by using the correct code wrapper of 
```bash
mkdir '{code}_dir' && mv '{code}' '{code}_dir/Solution.java' && cd '{code}_dir' && javac Solution.java && ulimit     -m {memory_limit} && ulimit -t {time_limit} && java Solution < '{input}'
```

for java.

A new problem is now seen where although the outputs of the test cases match, the result of the second case is marked as `None` indicating that some error was experienced in running the code. As to why it's raising an error while running is under investigation.

I suspect that one of the program limits are being violated causing a non zero exit code. Will investigate when I have time. @malavancs thank you for pointing this out.

**Comment by malavancs** [comment] 2018-01-28 14:13
I have another problem. In ubuntu 14.04. While compiling g++ program

> Adding attempt rayaamoapxsrgklgtylngrxunvpuwc to job queue
> 127.0.0.1 - - [28/Jan/2018 06:10:15] "POST /attempt HTTP/1.1" 200 69
> Checking attempt rayaamoapxsrgklgtylngrxunvpuwc
> False  /home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc: file not recognized: File format not recognized
> collect2: error: ld returned 1 exit status
> 
> Attempt rayaamoapxsrgklgtylngrxunvpuwc status None
> {'memory_limit': 50000, 'attempt_id': 'rayaamoapxsrgklgtylngrxunvpuwc', 'qpk': '1', 'time_limit': 1, 'commands': ["g++ '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc' -o '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc.compiled' && ulimit -m 50000 && ulimit -t 1 && '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc.compiled' <'/home/malavan/Desktop/ss/workspace/bqkqgyzdmcpsogliddxdoppflgxpjq'"], 'inp_paths': ['/home/malavan/Desktop/ss/workspace/bqkqgyzdmcpsogliddxdoppflgxpjq'], 'evaluated': True, 'code_path': '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc', 'out_list': ['1\n2\n3\n4\n5'], 'user': {'name': 'malavanhariss', 'password': 'sdff'}, 'status': [None]}

When i change the extension of the file "token.cpp", the command work.

> g++ '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc.**cpp**' -o '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc.compiled' && ulimit -m 50000 && ulimit -t 1 && '/home/malavan/Desktop/ss/workspace/rayaamoapxsrgklgtylngrxunvpuwc.compiled' <'/home/malavan/Desktop/ss/workspace/bqkqgyzdmcpsogliddxdoppflgxpjq'

**Comment by theSage21** [comment] 2018-01-28 14:46
This would also pertain to the wrapper. Before compiling we should move the file to the appropriate name like we do for Java. I'm currently in the process of resolving #30 and have solved this problem there.

If you can, @malavancs could you verify that increasing the `ulimits` with the new wrapper I posted for Java resolves this issue? We can then be sure of putting it in the next release.  `judge.py` is where the investigation will need to start.

**Comment by malavancs** [comment] 2018-01-28 15:21
Java still throwing the issue. 
And I solve the g++ issue by updating gcc and g++  wrapper.

```

   {
"gcc": "mv -n '{code}' '{code}.c' && gcc '{code}.c' -o '{code}.compiled' && ulimit -m {memory_limit} && ulimit -t {time_limit} && '{code}.compiled' <'{input}'" 
}
```
```
{
    "g++": "mv -n '{code}' '{code}.cpp' && g++ '{code}.cpp' -o '{code}.compiled' && ulimit -m {memory_limit} && ulimit -t {time_limit} && '{code}.compiled' <'{input}'"
}
```

**Comment by theSage21** [comment] 2018-01-28 16:01
1. Those wrappers should work.
2. What error is being thrown by the Java code?

**Comment by malavancs** [comment] 2018-01-28 17:43
```
127.0.0.1 - - [28/Jan/2018 09:41:30] "POST /attempt HTTP/1.1" 200 69
127.0.0.1 - - [28/Jan/2018 09:41:30] "POST /user/leader HTTP/1.1" 200 241
127.0.0.1 - - [28/Jan/2018 09:41:31] "POST /user/leader HTTP/1.1" 200 241
True Taorpebfeghr*arsain.eeglo*tla.r*e*atcem.etnacoh*i.*weph**rn.  ----------
Attempt bovwjvtrhldadvqxzstwuziurhillp status True
False  mkdir: cannot create directory ‘/home/malavan/Desktop/ss/workspace/bovwjvtrhldadvqxzstwuziurhillp_dir’: File exists
 ----------
Attempt bovwjvtrhldadvqxzstwuziurhillp status None
False  mkdir: cannot create directory ‘/home/malavan/Desktop/ss/workspace/bovwjvtrhldadvqxzstwuziurhillp_dir’: File exists
 ----------
Attempt bovwjvtrhldadvqxzstwuziurhillp status None
False  mkdir: cannot create directory ‘/home/malavan/Desktop/ss/workspace/bovwjvtrhldadvqxzstwuziurhillp_dir’: File exists
 ----------
Attempt bovwjvtrhldadvqxzstwuziurhillp status None
False  mkdir: cannot create directory ‘/home/malavan/Desktop/ss/workspace/bovwjvtrhldadvqxzstwuziurhillp_dir’: File exists
 ----------
Attempt bovwjvtrhldadvqxzstwuziurhillp status None
False  mkdir: cannot create directory ‘/home/malavan/Desktop/ss/workspace/bovwjvtrhldadvqxzstwuziurhillp_dir’: File exists
 ----------
Attempt bovwjvtrhldadvqxzstwuziurhillp status None

```

**Closed as completed** 2021-03-20 09:10 UTC
Labels: bug, next-release
